databases:
  - name: main-db
    region: ohio
    plan: free
    databaseName: teachhub_main_db
    user: root

services:
  - type: web
    name: core-service
    env: node
    repo: https://github.com/teach-hub/core-service.git
    region: ohio
    plan: free
    branch: main
    buildCommand: npm install && npx tsc
    startCommand: node dist/index.js
    numInstances: 1
    healthCheckPath: /
