services:
  - type: web
    name: core-service
    env: node
    repo: https://github.com/teach-hub/core-service.git # optional
    region: ohio
    plan: free
    branch: main
    buildCommand: npm install && npx tsc
    startCommand: node dist/index.js
    numInstances: 1
    healthCheckPath: /

databases:
  - name: core-service-db
    region: ohio
    plan: free
    databaseName: main_db_core_service
    user: root
